#Shubham Chandra
#Problem 8

text = "GTACGACGGAGTGTTATAAGATGGGAAATCGGATACCAGATGAAATTGTGGATCAGGTGCAAAAGTCGGCAGATATCGTTGAAGTCATAGGTGATTATGTTCAATTAAAGAAGCAAGGCCGAAACTACTTTGGACTCTGTCCTTTTCATGGAGAAAGCACACCTTCGTTTTCCGTATCGCCCGACAAACAGATTTTTCATTGCTTTGGCTGCGGAGCGGGCGGCAATGTTTTCTCTTTTTTAAGGCAGATGGAAGGCTATTCTTTTGCCGAGTCGGTTTCTCACCTTGCTGACAAATACCAAATTGATTTTCCAGATGATATAACAGTCCATTCCGGAGCCCGGCCAGAGTCTTCTGGAGAACAAAAAATGGCTGAGGCACATGAGCTCCTGAAGAAATTTTACCATCATTTGTTAATAAATACAAAAGAAGGTCAAGAGGCACTGGATTATCTGCTTTCTAGGGGCTTTACGAAAGAGCTGATTAATGAATTTCAGATTGGCTATGCTCTTGATTCTTGGGACTTTATCACGAAATTCCTTGTAAAGAGGGGATTTAGTGAGGCGCAAATGGAAAAAGCGGGTCTCCTGATCAGACGCGAAGACGGAAGCGGATATTTCGACCGCTTCAGAAACCGTGTCATGTTTCCGATCCATGATCATCACGGGGCTGTTGTTGCTTTCTCAGGCAGGGCTCTTGG"

#count characters
def count(a, string):
    count = 0
    for char in string:
        if char == a:
            count += 1
    return count

#find the number of a, t, g, c

count_a = count("A",text)
count_t = count("T",text)
count_g = count("G",text)
count_c = count("C",text)

# find as percentages
perc_a = count_a/len(text)*100
perc_t = count_t/len(text)*100
perc_g = count_g/len(text)*100
perc_c = count_c/len(text)*100

#print the needed %'s

print(f"A: {perc_a:.0f}%")
print(f"T: {perc_t:.0f}%")
print(f"C: {perc_c:.0f}%")
print(f"G: {perc_g:.0f}%")


